cd /public/home/caizhy/work/NIID-Bench-main/
python novel_exp.py --model=vit \
	--dataset=cifar10 \
	--alg=fedPer \
	--lr=0.01 \
	--comm_round=1\
	--batch-size=64 \
	--n_parties=50 \
	--epochs=5 \
	--chunk_len=5 \
	--rho=0.9 \
	--depth=6 \
	--partition=noniid-labeldir \
	--device='cuda:0'\
	--datadir='./data/' \
	--logdir='./logs_exp/' \
	--init_seed=0\
	--test_round=2\
	--eval_step=1\
	--sample=0.1\
	--save_model